/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface IiifThumbnail {
        "height": string;
        "src": string;
        "width": string;
    }
}
declare global {
    interface HTMLIiifThumbnailElement extends Components.IiifThumbnail, HTMLStencilElement {
    }
    var HTMLIiifThumbnailElement: {
        prototype: HTMLIiifThumbnailElement;
        new (): HTMLIiifThumbnailElement;
    };
    interface HTMLElementTagNameMap {
        "iiif-thumbnail": HTMLIiifThumbnailElement;
    }
}
declare namespace LocalJSX {
    interface IiifThumbnail {
        "height"?: string;
        "src"?: string;
        "width"?: string;
    }
    interface IntrinsicElements {
        "iiif-thumbnail": IiifThumbnail;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "iiif-thumbnail": LocalJSX.IiifThumbnail & JSXBase.HTMLAttributes<HTMLIiifThumbnailElement>;
        }
    }
}
